### ISSUE TITLE
Support MinIO as storage provider

### ISSUE THREAD

**Issue by Lukas-Sachse** [ducktors/turborepo-remote-cache#149]
## 🚀 Feature Proposal

Add support for MinIO as storage provider.

## Motivation

We have a running MinIO instance and want to use it for our remote cache.
I tried to use it with the AWS S3 Storage Provider docs, but I can't get it working. 
So I think there are maybe some additional settings or steps needed.

## Example
Adding specific doc section for MinIO.

**Comment by eve0415** [comment]
I don't have my AWS account so I cannot test it myself but I don't think we have to wrap endpoint around `aws.Endpoint` but pass it directly

https://github.com/ducktors/turborepo-remote-cache/blob/9eb43798bf36f5b0707ac50d667da7042a9f720a/src/plugins/remote-cache/storage/s3.ts#L31

```diff
--- a/src/plugins/remote-cache/storage/s3.ts
+++ b/src/plugins/remote-cache/storage/s3.ts
@@ -28,8 +28,8 @@ export function createS3({
         }
       : {}),
     ...(region ? { region } : {}),
-    ...(endpoint ? { endpoint: new aws.Endpoint(endpoint) } : {}),
+    ...(endpoint ? { endpoint } : {}),
       ? { sslEnabled: false, s3ForcePathStyle: true }
       : {}),
   })
```

After changing the line, it should work with [MinIO](https://min.io/) and [Cloudflare R2](https://developers.cloudflare.com/r2/api/s3/api/) as well.

**Comment by hieuvuvan** [comment]
it related to option `s3ForcePathStyle: true`. i workaround using `NODE_ENV=test`
