### ISSUE TITLE
Current state of main branch is not deployable to vercel.

### ISSUE THREAD

**Issue by trm217** [ducktors/turborepo-remote-cache#159]
## 🐛 Bug Report

I attempted to deploy this repo via the deploy to vercel button, that however yielded an exception during build (see screenshot). I later attempted to deploy it again via fork, which didn't work either, resulting in the same error.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/30313631/228841876-ef6f3f0f-49eb-470a-a8ed-381168e7a5ca.png">

## To Reproduce

Fork the repository, deploy the forked repo to vercel, done.

## Expected behavior

Build and start on vercel without an exception

## Your Environment

Vercel 🤷🏻‍♂️

**Comment by matteovivona** [comment]
Link to this https://github.com/ducktors/turborepo-remote-cache/issues/154
