### ISSUE TITLE
Remote caching disabled since turbo 1.9.4

### ISSUE THREAD

**Issue by albertehc** [ducktors/turborepo-remote-cache#170]
## 🐛 Bug Report

Remote caching disabled since turbo 1.9.4

## To Reproduce

Upgrade to >1.9.3 version

## Expected behavior

Get Remote caching enabled

Since upgrade turborepo to 1.9.4 no way to get remove caching enable, someone have a fix or can reproduce the problem? thanks

**Comment by dobesv** [comment]
Are you getting any errors from the client or server?  You can run turbo in a more verbose mode to get it to log information about when it tries to cache.

**Comment by NigelBreslaw** [comment]
It seems turborepo removed support for .turbo/config.json
I had to delete that file and set the needed properties per script in the root package.json e.g. `turbo -v --team=team_example  --token=ExampleToken --api=https://example.remote.cache.com build`

**Comment by dobesv** [comment]
Oh interesting.  You can also use environment variables, that's what we do.  `TURBO_API`, `TURBO_TEAMID`, `TURBO_TOKEN`.

**Comment by fox1t** [comment]
We updated our docs to reflect this change a while ago. You can find the new version on the website https://ducktors.github.io/turborepo-remote-cache/custom-remote-caching
