### ISSUE TITLE
Incompatible with Yarn/npm, or Node <18 

### ISSUE THREAD

**Issue by TheSonOfThomp** [ducktors/turborepo-remote-cache#178]
**Please read this entire template before posting any issue. If you ignore these instructions
and post an issue here that does not follow the instructions, your issue might be closed,
locked, and assigned the `missing discussion` label.**

## 🐛 Bug Report

Since v1.14.2, users of yarn or npm can't install this package. 
Consumers using node<18 also can't install this package

This is the error message
```
error turborepo-remote-cache@1.14.3: The engine "node" is incompatible with this module. Expected version ">=18". Got "16.20.0"
warning turborepo-remote-cache@1.14.3: The engine "pnpm" appears to be invalid.
error Found incompatible module.
```

## To Reproduce

- In any yarn or npm project, run
```bash
yarn add turborepo-remote-cache
```
or
```bash
npm install turborepo-remote-cache
```

## Expected behavior

Should intall

## Your Environment

- _os_: Mac
```
nvm current
v16.20.0

yarn --version
1.22.19
```

**Comment by matteovivona** [comment]
@TheSonOfThomp fixed. thank for your report
