### ISSUE TITLE
azure-storage has been deprecated

### ISSUE THREAD

**Issue by matteovivona** [ducktors/turborepo-remote-cache#186]
`npm WARN deprecated azure-storage@2.10.7: Please note: newer packages @azure/storage-blob, @azure/storage-queue and @azure/storage-file are available as of November 2019 and @azure/data-tables is available as of June 2021. While the legacy azure-storage package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Migration guide can be found: https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/MigrationGuide.md`

**Comment by Talent30** [comment]
```ts
async createReadStream(artifactPath) {
      const read = await blobService
        .getContainerClient(containerName)
        .getBlobClient(artifactPath)
        .download();

      const stream = new Readable().wrap(read!.readableStreamBody!);

      return stream as NodeJS.ReadStream;
    },
createWriteStream(artifactPath) {
      return blobService
        .getContainerClient(containerName)
        .getBlobClient(artifactPath).getBlockBlobClient().uploadStream();
    },
```

I gave a go, the new sdk design is awful IMO...you have to pass a Readable to `uploadStream(readable)` Any suggestion to make it work without change too much code?
