### ISSUE TITLE
Option to log to file

### ISSUE THREAD

**Issue by puug** [ducktors/turborepo-remote-cache#190]
## 🚀 Feature Proposal

Ability to specify a log mode, with file being an available option, alongside an option to set the file location.

## Motivation

When running on docker in some environments, there's limited support for some of the docker log-driver options. A general purpose way to collect logs in these scenarios is to log to disk and collect by an agent on the host via a mount.

## Example

ie new environment variable options
```
LOG_MODE=file
LOG_FILE=/path/to/my/file.log
```

**Comment by matteovivona** [comment]
@puug I hope this is okay. In case you can open a new PR
