### ISSUE TITLE
Not running in AWS EC2 T4g instance

### ISSUE THREAD

**Issue by maurobender** [ducktors/turborepo-remote-cache#360]
[The latest uploaded image to Docker Hub](https://hub.docker.com/layers/ducktors/turborepo-remote-cache/latest/images/sha256-d775e798ca801f16a8713cbf00107966e529e5825bcaabe4ae664577ab7d454b?context=explore) seems to don't have support for arm64 architecture.

Previous images v2.1.2 and 2.1.1 seem to have support for arm64 but I'm getting the same error when running them in the T4g instance.

Image v2.1.0 has support and works fine in the instance.

## 🐛 Bug Report

Trying to run the image in a [AWS t4g instance](https://aws.amazon.com/ec2/instance-types/t4/) (arm64 based) does not work, the logs show the following error:

```
exec /usr/bin/dumb-init: exec format error
```

## To Reproduce

Run the image using docker in a arm64 based machine.

## Expected behavior

The image running without errors.

## Your Environment

- _os_: Linux 22.04.1-Ubuntu SMP Fri Apr  5 17:56:39 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux

**Comment by matteovivona** [comment]
There was a bug in the docker image creation step only for latest tag. As workaround, use latest version with a semver tag.

Let me know

**Comment by thekevinbrown** [comment]
@matteovivona I experienced this issue and your workaround worked for me. Are there plans to update the docker image creation step for the latest tag to fix the issue?

**Comment by matteovivona** [comment]
@thekevinbrown unfortunately, the official docker action cannot push the latest on multi arch. so since it was not even a correct approach to use the latest, we simply deleted the tag

**Comment by thekevinbrown** [comment]
No worries, thanks for the info!
