### ISSUE TITLE
Adding teamId in .turbo/config.json file is not working, turborepo is not passing team or slug value in API calls

### ISSUE THREAD

**Issue by amit-y11** [ducktors/turborepo-remote-cache#456]
## 🐛 Bug Report

I added the `teamid`, `apiurl` and `token` in .turbo/config.json file as specified in the [docs](https://ducktors.github.io/turborepo-remote-cache/custom-remote-caching.html#config-file), but getting the error that `querystring should have required property 'team'` 
```js
{"severity":"INFO","level":30,"time":1729612938144,"pid":1143396,"hostname":"ip-172-00-00-00.ap-south-1.compute.internal","reqId":"n4FB_7ioRG2Hu9yb9GDI8Q-191","req":{"method":"PUT","url":"/v8/artifacts/259aba3e7ee3e3da","hostname":"localhost:6000","remoteAddress":"127.0.0.1","remotePort":41528},"message":"incoming request"}
{"severity":"WARNING","level":40,"time":1729612938189,"pid":1143396,"hostname":"ip-172-00-00-00.ap-south-1.compute.internal","reqId":"n4FB_7ioRG2Hu9yb9GDI8Q-191","data":null,"isBoom":true,"isServer":false,"output":{"statusCode":400,"payload":{"statusCode":400,"error":"Bad Request","message":"querystring should have required property 'team'"},"headers":{}},"stack":"Error: querystring should have required property 'team'\n    at Object.handler (file:///home/ec2-user/turborepo-remote-cache/dist/plugins/remote-cache/routes/put-artifact.js:12:19)\n    at preHandlerCallback (/home/ec2-user/turborepo-remote-cache/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/handleRequest.js:128:37)\n    at preValidationCallback (/home/ec2-user/turborepo-remote-cache/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/handleRequest.js:112:5)\n    at handler (/home/ec2-user/turborepo-remote-cache/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/handleRequest.js:76:7)\n    at /home/ec2-user/turborepo-remote-cache/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/contentTypeParser.js:189:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:206:9)\n    at done (/home/ec2-user/turborepo-remote-cache/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/contentTypeParser.js:183:14)\n    at /home/ec2-user/turborepo-remote-cache/node_modules/.pnpm/fastify@4.12.0/node_modules/fastify/lib/contentTypeParser.js:270:27\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","type":"Error","message":"querystring should have required property 'team'"}
{"severity":"INFO","level":30,"time":1729612938190,"pid":1143396,"hostname":"ip-172-00-00-00.ap-south-1.compute.internal","reqId":"n4FB_7ioRG2Hu9yb9GDI8Q-191","res":{"statusCode":400},"responseTime":45.80773687362671,"message":"request completed"}
```

## To Reproduce

- Add the `teamid`, `apiurl` and `token` in .turbo/config.json
- Run the cache server
- delete your local cache from .turbo directory
- run build command in your project to trigger saving cache in remote server
- check logs for the error

```js
 {
   "teamid": "ducktors",
   "token": "token",
   "experimentalUI": false,
   "apiurl": "link to your cache server"
 }

```

## Expected behavior

The teamid value should be passed during the API calls to the cache server

## Workaround
Passing the teamid in the package.json file works correctly
```json
  "build": "turbo run build --team=\"ducktors\"",
```
Although it should be `team` and not `teamid` (In docs it is shown teamid)

## Your Environment

- _OS_: AWS Linux (EC2 Instance)
- _Cloud Vendor_: AWS
- _Turbo Version_: 2.2.3

**Comment by mattref** [comment]
I've only tried this in the `.turbo/config.json` that resides in my project's root (haven't tried this in my "turbo global config"), but what fixed this issue for me was changing `teamid` to **`teamslug`**.

After looking around in [Turborepo's source code](https://github.com/vercel/turborepo/blob/1b1e46c7ca64d055d4d0eeb6a8e25c6e6c88bada/crates/turborepo-lib/src/config/mod.rs#L224-L228), I noticed a comment stating that `teamslug` corresponds to the `TURBO_TEAM` environment variable, whereas `teamid` corresponds to `TURBO_TEAMID`. Given that Turborepo Remote Cache documentation references only `TURBO_TEAM`, I figured `teamslug` would solve the issue, and it did.

**Comment by matteovivona** [comment]
@mattref would you be so kind as to open a PR with the updated documentation? Unfortunately Vercel constantly changes variable names or their usage. Thank you!
