### ISSUE TITLE
When storage provider is LOCAL and path is set still uses tmp directory

### ISSUE THREAD

**Issue by tm1000** [ducktors/turborepo-remote-cache#62]
## 🐛 Bug Report

When using `STORAGE_PROVIDER: "LOCAL"` and `STORAGE_PATH: "/my/custom/path"`. The turborepo remote cache server prefixes the system tmp drive onto the path

The bug can be seen here: https://github.com/ducktors/turborepo-remote-cache/blob/d81d7ef79b55bd9f01fd29419074725b5435b08d/src/plugins/remote-cache/storage/local.ts#L10

`path` is filled with what I sent however it's prefixed by `tmpdir()`

**Comment by fox1t** [comment]
Hi! This is a good point. 
Maybe adding another parameter to the options of the `createLocal` function:
```
export type LocalOptions = {
  path: string,
  useTmp: boolean
}
```
and an env var `TURBO_CACHE_USE_TMP_FOLDER` (boolean) that defaults to true (for backside compatibility), and that is assigned to that `useTmp` value (https://github.com/ducktors/turborepo-remote-cache/blob/d81d7ef79b55bd9f01fd29419074725b5435b08d/src/plugins/remote-cache/storage/index.ts#L40). 

What do you think?

**Comment by tm1000** [comment]
@fox1t I issued a PR from your comments it seemed good to me
