### ISSUE TITLE
Storage limit support?

### ISSUE THREAD

**Issue by mjarkk** [ducktors/turborepo-remote-cache#64]
## 🚀 Feature Proposal

Is there a way I can limit the amount of storage that is used and if not is there any change this feature might get added?

## Motivation

I only have a finite amount of cloud storage and I'm worried using this will quickly fill up all my cloud storage.
So I would like to set a limit to the amount of storage the cache can take up.

## Example

I would like to have for example a remote cache with a maximum of 20 GiB
If that size is reached and new cache entries are added the oldest caches are removed.

## Alternatives

I presume I can clear the cache myself and I would accept to do that once a week / month but there Is currently no documentation on this :(

**Comment by fox1t** [comment]
Hi! I like this feature. It can be tricky to implement since we support several storage targets and deployment environments. Do you have something in mind?

Which storage provider are you using?

**Comment by tehKapa** [comment]
We currently save the cache in an S3 bucket, and to clean up the old cache, we have set up a lifecycle rule at the bucket level. It is the easiest thing to do and all the major providers support it https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-lifecycle-mgmt.html

**Comment by fox1t** [comment]
I am closing this for no further follow-up.
