### ISSUE TITLE
add status endpoint for health probe

### ISSUE THREAD

**Issue by devtribe** [ducktors/turborepo-remote-cache#80]
## 🚀 Feature Proposal

Add a status endpoint, like this [one](https://vercel.com/docs/rest-api#endpoints/artifacts/get-status-of-remote-caching-for-this-principal).
For a first Version it would be sufficient if the response is always `enabled`

## Motivation

For kubernetes we need some kind of liveness probe to see if the server is ready to accept traffic. This would be an easy fix to support it.

## Example

See https://vercel.com/docs/rest-api#endpoints/artifacts/get-status-of-remote-caching-for-this-principal

**Comment by fox1t** [comment]
I like the idea, and we need probes routes. It would be nice also to implement the other endpoints (link and login) in the future.

@devtribe, do you know the response for Vercel's implementation?
