### ISSUE TITLE
Unable to use for different repo ?

### ISSUE THREAD

**Issue by zigang93** [ducktors/turborepo-remote-cache#83]
Hi, I had deploy docker version
I just found out that can't share same remote cache server for different repo..

Example:
example.com <--- this is my custom remote cache server

repo A -- build command: "turbo build --team=\"team_A\" --token=\"token\" --api=\"http://example.com\""
repo B -- build command: "turbo build --team=\"team_B\" --token=\"token\" --api=\"http://example.com\""

repoe B cannot remote cache..
from my custom remote cache server .. it show `Artifact not found` error

it is cannot use different repo with different team? 

## Expected behavior

Should be able to use remote cache even different repo

## Your Environment

- _os_: Mac
- _any other relevant information_

**Comment by zigang93** [comment]
look like.. my build output too huge..
```zsh
ck":"Error: aborted\n    at connResetException (node:internal/errors:704:14)\n    at abortIncoming (node:_http_server:625:17)\n    at socketOnClose (node:_http_server:619:3)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at TCP.<anonymous> (node:net:757:14)","type":"Error","message":"aborted"}
{"severity":"INFO","level":30,"time":1669020326933,"pid":7,"hostname":"9367e1334340","reqId":"iCMKHAI6RbWB0Lvh_YOx2Q-4","req":{"method":"PUT","url":"/v8/artifacts/c188f7d65bba59fc?slug=wcs_web","hostname":"54.254.8.23:4200","remoteAddress":"121.121.42.97","remotePort":58566},"message":"incoming request"}
{"severity":"INFO","level":30,"time":1669020350970,"pid":7,"hostname":"9367e1334340","reqId":"iCMKHAI6RbWB0Lvh_YOx2Q-5","req":{"method":"PUT","url":"/v8/artifacts/c188f7d65bba59fc?slug=wcs_web","hostname":"54.254.8.23:4200","remoteAddress":"121.121.42.97","remotePort":58573},"message":"incoming request"}
{"severity":"ERROR","level":50,"time":1669020352851,"pid":7,"hostname":"9367e1334340","reqId":"iCMKHAI6RbWB0Lvh_YOx2Q-4","code":"ECONNRESET","statusCode":400,"stack":"Error: aborted\n    at connResetException (node:internal/errors:704:14)\n    at abortIncoming (node:_http_server:625:17)\n    at socketOnClose (node:_http_server:619:3)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at TCP.<anonymous> (node:net:757:14)","type":"Error","message":"aborted"}

```

I had use `BODY_LIMIT=304857600` to overwrite .. but still same error..

**Comment by fox1t** [comment]
Did you figure out what the issue was?

**Comment by NorkzYT** [comment]
@zigang93 
Could you please advise what your fix to the issue was?
