### ISSUE TITLE
Emit d.ts files in build

### ISSUE THREAD

**Issue by tom-fletcher** [ducktors/turborepo-remote-cache#88]
## 🚀 Feature Proposal

Emit `d.ts` files in build.

## Motivation

The build process doesn't currently output any `d.ts` files. This means that when using the `npm` package in a typescript project, you have to add a new declaration file containing `declare module 'turborepo-remote-cache/build/app';`

As the project is written in typescript, it would be nicer to output the types by adding to `tsconfig.json`:

```diff
{
  "compilerOptions": {
    ...
+   "declaration": true,
  }
}
```

## Example

Writing a proxy for the server (such as an AWS Lambda Function) in typescript.

**Comment by fox1t** [comment]
Hi! Thanks for pointing this out. Can you please explain how you are using this project as a lib? One thing we want to do soon is to make it a monorepo which will contain a fastify-plugin that can be consumed as a lib. So I am interested in exploring your specific use case to consider it during this refactor.
