### ISSUE TITLE
Missing "storage.objects.delete" permission for GCP ?

### ISSUE THREAD

**Issue by Klaitos** [ducktors/turborepo-remote-cache#95]
Hello,

I have set up the remote cache since one week in our GCP environment now. First, thanks for the amazing implementation, its rocks.

I observe some `Error during the artifact creation` error in the output logs with the error description : `[service-account] does not have storage.objects.delete access to the Google Cloud Storage object`. My service account has two roles as mentioned in the doc : `Storage Object Creator` and `Storage Object Viewer`. 

Is it a required permission but not mentioned in the set up doc or am i missing something ? (i will add the permission on my side, but i want to fully understand this)

Using version `v1.10.1` running in docker container with gcp bucket inside a Cloud Run (application default credentials).

**Comment by fox1t** [comment]
Can you add that permission and check if the error goes away? If so, we should update the documentation! 
Thanks for pointing this out.

**Comment by Klaitos** [comment]
Yes I replaced the two roles of the documentation `Storage Object Creator` and `Storage Object Viewer` by `Storage Object Admin` (the role should be attached on the bucket only for this service account, not the service account itself) and the error is gone.
